version: "3"

services:
  help:
    image: "gmetrixr/baseimage:node-16-dev-v1"
    container_name: gmetri_webdis-commands
    command: ["tail", "-f", "/dev/null"]
    working_dir: /src
    user: node
    ports:
      - "8001:8001" #Format: HOST:CONTAINER
    volumes:
      - .:/src
      #Allow running host to run git commands:
      - ~/.ssh:/home/node/.ssh:ro
      - ~/.gitconfig:/home/node/.gitconfig:ro
    environment:
      - IS_LOCAL=true
      - BUILD_VERSION=localversion
      - NAMESPACE=local

networks:
  default:
    external:
      name: gmetri
